environment: development

server:
  port: 8080
  host: 0.0.0.0
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 30s
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]
    allow_credentials: true

database:
  driver: json
  dsn: /var/log/oceanproxy/proxies.json
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m

redis:
  addr: localhost:6379
  password: ""
  db: 0

logger:
  level: info
  format: json

auth:
  bearer_token: ${BEARER_TOKEN}
  jwt_secret: ${JWT_SECRET}
  token_ttl: 24h

providers:
  proxies_fo:
    api_key: ${PROXIES_FO_API_KEY}
    base_url: https://app.proxies.fo
    timeout: 30s
  nettify:
    api_key: ${NETTIFY_API_KEY}
    base_url: https://api.nettify.xyz
    timeout: 30s

proxy:
  domain: oceanproxy.io
  start_port: 10000
  end_port: 20000
  config_dir: /etc/3proxy
  log_dir: /var/log/oceanproxy
  script_dir: ./scripts
  nginx_conf_dir: /etc/nginx/conf.d