# Region/Subdomain Configurations
# Defines subdomains, their outbound ports, and associated plan types

regions:
  usa:
    subdomain: usa
    domain_suffix: oceanproxy.io
    outbound_port: 1337
    description: "United States proxies"
    plan_types:
      - proxies_fo_usa_residential
    nginx_config_file: oceanproxy_usa.conf
    
  eu:
    subdomain: eu
    domain_suffix: oceanproxy.io
    outbound_port: 1338
    description: "European Union proxies"
    plan_types:
      - proxies_fo_eu_residential
    nginx_config_file: oceanproxy_eu.conf
    
  alpha:
    subdomain: alpha
    domain_suffix: oceanproxy.io
    outbound_port: 9876
    description: "Alpha region proxies"
    plan_types:
      - nettify_alpha_residential
    nginx_config_file: oceanproxy_alpha.conf
    
  # Easy to add new regions
  beta:
    subdomain: beta
    domain_suffix: oceanproxy.io
    outbound_port: 8765
    description: "Beta region proxies"
    plan_types:
      - nettify_beta_datacenter
    nginx_config_file: oceanproxy_beta.conf
    
  datacenter:
    subdomain: datacenter
    domain_suffix: oceanproxy.io
    outbound_port: 1339
    description: "Datacenter proxies"
    plan_types:
      - proxies_fo_datacenter
    nginx_config_file: oceanproxy_datacenter.conf

  isp:
    subdomain: isp
    domain_suffix: oceanproxy.io
    outbound_port: 1340
    description: "ISP proxies"
    plan_types:
      - proxies_fo_usa_isp
    nginx_config_file: oceanproxy_isp.conf

  mobile:
    subdomain: mobile
    domain_suffix: oceanproxy.io
    outbound_port: 7654
    description: "Mobile proxies"
    plan_types:
      - nettify_alpha_mobile
    nginx_config_file: oceanproxy_mobile.conf

  unlimited:
    subdomain: unlim
    domain_suffix: oceanproxy.io
    outbound_port: 6543
    description: "Unlimited residential proxies"
    plan_types:
      - nettify_alpha_unlimited
    nginx_config_file: oceanproxy_unlimited.conf